### ISSUE TITLE
Possibility to have multiple (stacked?) Notifications

### ISSUE THREAD

**Issue by JulianFeinauer** [stimulus-components/stimulus-notification#2]
Hi, aweseome work!
Would it be possible to extend the behavior to allow multiple notifications to be active at once.
E.g. by stacking them on top of each other or else?
Or should / could this be done by another controller that simply handles the orientation of all messages?

If we find a good idea on how to achieve that I would be happy to contribute : )

**Comment by JulianFeinauer** [comment]
Okay I just realized that all of that is already possible via changes in the css... but I think it would make sense to add an example for that in the docs for others, what do you think?

**Comment by guillaumebriday** [comment]
Hey, yes it's only CSS dependent feature as long as each notification is a single instance of the Stimulus controller here 👍 

If you want to provide examples in the docs that would be cool! Could you open a PR please?
