### ISSUE TITLE
Open hidden notification via JavaScript

### ISSUE THREAD

**Issue by NiklasMerz** [stimulus-components/stimulus-notification#3]
We have a custom stimulus controller that needs to open notifications.

It would be nice to have the option to make notifications that are hidden by default and can be opened via JavaScript.

**Comment by guillaumebriday** [comment]
Cool idea! Shouldn't be that hard to do, will try to find some time to do it!

**Comment by guillaumebriday** [comment]
Done https://github.com/stimulus-components/stimulus-notification/releases/tag/v2.1.0

thanks @NiklasMerz for the suggestion
